CREATE PROCEDURE dbo.TEST(@STDR_YEAR VARCHAR(MAX), @ID VARCHAR(MAX))
AS
BEGIN

 DECLARE @RESULT NVARCHAR(MAX);

 DECLARE @SQL  NVARCHAR(MAX);
 DECLARE @SQL_RESULT NVARCHAR(MAX);

 SET @SQL_RESULT = N'@TEMP_RESULT VARCHAR(MAX) OUTPUT';  

 SET @SQL = N'SELECT @TEMP_RESULT = VALUE FROM dbo.[' + @STDR_YEAR + '] WHERE ID =' + @ID 

 EXEC SP_EXECUTESQL @SQL, @SQL_RESULT,
      @TEMP_RESULT =  @RESULT OUTPUT;
	
	SELECT @RESULT;

END
